# App name
spring.application.name=job-portal

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/job_portal_db
spring.datasource.username=root
spring.datasource.password=root

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server port
server.port=8081

# Cloudinary
cloudinary.cloud-name=dos5ssicb
cloudinary.api-key=642835989124544
cloudinary.api-secret=z0q_MzYJ8CwwPLiNixz-BCtbxto

# OpenAI
openai.api.key=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